### ISSUE TITLE
Derived languages are not supported

### ISSUE THREAD

**Issue by BrunoMine** [minetest-mods/intllib#9] opened 2016-08-11 17:33 UTC
Minetest has support for pt_BR but intllib not. That's a big inconvenience for me. In this situation we have two problems:
- The selected language will not be understood correctly
- Translators are required to choose only one primary language (eg Portuguese in Portugal or Portuguese in Brazil)
  I hope this is resolved soon

**Comment by kaeza** [comment] 2016-10-06 08:32
Take a look at the [ll_CC](https://github.com/minetest-mods/intllib/tree/ll_CC) branch and tell me if that fixes the problem.

You can have both `pt_BR.txt` and `pt.txt` (the latter being the default dialect).

**Comment by BrunoMine** [comment] 2016-10-06 10:12
I performed the tests. The problem still occurs.
I'm using a test mod that already works with intllib (I changed the `pt` locale file to `pt_BR`).
Language Minetest configuration (`language`) = `pt_BR`
intlib is not translating.

I want to take the opportunity to ask another feature.
If linguegem `ll` not exist, intllib should seek any `ll_CC` language (derived from `ll` language configured in the game)

**Comment by kaeza** [comment] 2016-10-06 23:42
> I performed the tests. The problem still occurs.

Gah, fixed and force-pushed to `ll_CC` branch. I can confirm it works now.

> If linguegem `ll` not exist, intllib should seek any `ll_CC` language (derived from `ll` language configured in the game)

That would require huge kludges, as you cannot infer the country code from language code. You have things like `es_ES` and `pt_PT`, which are just the language code in uppercase. but then there's no such thing as `en_EN`, for example.

Since many countries may speak the same language (e.g. `es_ES`, `es_UY`, `es_AR`, `es_MX`, ...), and some countries speak multiple languages (e.g. `en_CA`, `fr_CA`), you cannot assume anything.

As an example above, I may select `ll_LL`, but would break for english (there's no `en_EN`; the "default" would be `en_GB`). If we use the first derivative found, you could get `en_CA` (Canadian english), or `de_AU` (Austrian german), which may not be what you expect.

It's not worth the effort to support "smart" detection like that, IMHO, but feel free to provide an implementation if you feel like it.

**Comment by kaeza** [comment] 2016-10-08 00:52
@BrunoMine Can you confirm the issue is fixed?

**Comment by BrunoMine** [comment] 2016-10-08 01:13
You can use a very simple algorithm to search for a secondary language.

``` lua
local minetest_language = "pt" -- minetest settings
local intllib_language = "?" -- intllib choice for secondary language
local locale_list = minetest.get_dir_list(minetest.get_modpath("modname").."/locale")
for n, lang in ipairs(locale_list) do
    if string.find(lang, minetest_language.."_") then
        intllib_language = lang
        break
    end
end
```

I do not know if you could understand what I want.
Do you think a good idea?

EDIT:
Yes, the initial problem was solved

**Comment by kaeza** [comment] 2016-10-08 03:08
I understand what you suggest, but I don't think that's the correct way. Can you open a separate issue for that so others can comment?

I'm going to close this one since the original problem is fixed.

**Closed as completed by kaeza** 2016-10-08 03:08 UTC
